exclude: '^package.json|package-lock.json|.*?\.tsv$'
fail_fast: true 
repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1
    hooks:
        - id: commitizen
          stages: [commit-msg]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
        stages: [commit]
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
    -   id: golangci-lint
        stages: [commit]
-   repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3 # pragma: allowlist secret
    hooks:
      - id: go-unit-tests
        stages: [commit]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-json
        stages: [commit]
      #-   id: no-commit-to-branch
      #    args: ['--branch', 'main']
      #    stages: [commit]
    -   id: pretty-format-json
        args: ['--autofix']
        stages: [commit]
    -   id: check-merge-conflict
        stages: [commit]
    -   id: check-yaml
        stages: [commit]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
    -   id: markdownlint-fix
        stages: [commit]
        args: ["--ignore", "README.md"] # This is a generated file
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
    -   id: shellcheck
        stages: [commit]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.0.0-alpha.2'
    hooks:
    -   id: eslint
        stages: [commit]
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: 'v0.5.1'
    hooks:
      - id: go-mod-tidy
