repos:
-   repo: https://github.com/Contrast-Labs/detect-secrets
    rev: v1.1.2
    hooks:
    -   id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ['--baseline', '.secrets.baseline']
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.49.0
    hooks:
    -   id: golangci-lint
-   repo: https://github.com/Bahjat/pre-commit-golang    
    rev: v1.0.3 # pragma: allowlist secret
    hooks:
      - id: go-unit-tests
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-added-large-files
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-yaml
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
    -   id: markdownlint-fix
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
    -   id: shellcheck