name: Package Benchmarks
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  benchmark:
    name: Execute Benchmarks
    uses: devnw/workflows/.github/workflows/make-bench.yml@main
    secrets: inherit # pragma: allowlist secret
