name: Update README with Go documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  pull-requests: write
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Fix Git repository permissions
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Fix workspace permissions
      run: sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE

    - name: Update readme according to Go doc
      uses: posener/goreadme@v1
      with:
        email: "41898282+github-actions[bot]@users.noreply.github.com"
        recursive: true
        constants: true
        variabless: true
        functions: true
        types: true
        factories: true
        credit: false
        # Optional: Token allows goreadme to comment the PR with diff preview.
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
