name: Update README with Go documentation

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Generate Go documentation and update README
      run: |
        if ! grep -q '<!-- GODOC_START -->' README.md; then
          echo "Error: <!-- GODOC_START --> marker not found in README.md"
          exit 1
        fi

        go install github.com/robertkrimen/godocdown/godocdown@latest
        TEMPFILE=$(mktemp)
        echo "<!-- GODOC_START -->" > $TEMPFILE
        godocdown . >> $TEMPFILE
    
    
        awk -v file="$TEMPFILE" \
            '/<!-- GODOC_START -->/, /<!-- GODOC_END -->/ { if ($0 ~ /<!-- GODOC_END -->/) { while (getline < file) print } else { next } } 1' \
            README.md > README.md.new
    
        mv README.md.new README.md

    - name: Create or update pull request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "docs(README.md): update go documentation"
        title: "Update Go documentation in README"
        body: "This PR updates the Go documentation in the README."
        branch: "update-go-documentation"
        base: "main"
        labels: "documentation,automerge"
