name: Update README with Go documentation

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Update readme according to Go doc
      uses: posener/goreadme@v1
      with:
        email: "<41898282+github-actions[bot]@users.noreply.github.com>"
        recursive: true
        constants: true
        variabless: true
        functions: true
        types: true
        factories: true
        badge-codecov: 'true'
        badge-godoc: 'true'
        badge-goreadme: 'true'
        badge-goreportcard: 'true'
        author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        # Optional: Token allows goreadme to comment the PR with diff preview.
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
