name: Update README with Go documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  pull-requests: write
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure safe directory for Git
      run: git config --global --add safe.directory /github/workspace

    - name: Update readme according to Go doc
      uses: posener/goreadme@v1
      with:
        recursive: true
        constants: true
        variabless: true
        functions: true
        types: true
        factories: true
        badge-codecov: 'true'
        badge-godoc: 'true'
        badge-goreportcard: 'true'
        email: "41898282+github-actions[bot]@users.noreply.github.com"
        # Optional: Token allows goreadme to comment the PR with diff preview.
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
