name: Update README with Go documentation

on:
  push:
    branches:
      - main
jobs:
  update-readme:
    name: Update README with Go documentation
    uses: devnw/workflows/.github/workflows/docs.yml@main
    secrets: inherit # pragma: allowlist secret
